# Generated by Django 2.2.8 on 2019-12-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipfsfile",
            name="ipfs_hash",
            field=models.CharField(max_length=46),
        ),
    ]
